import OrcaDomain

typealias TranscriptRole = OrcaTranscriptRole
typealias TranscriptDeliveryState = OrcaTranscriptDeliveryState
typealias TranscriptMessage = OrcaTranscriptMessage
typealias TurnRetryIdentity = OrcaTurnRetryIdentity
typealias RuntimeReceipt = OrcaRuntimeReceipt
typealias ConversationState = OrcaConversationState
typealias RuntimeConnectionState = OrcaRuntimeConnectionState
